spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orivehrm
    username: root
    password: Orive@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ORGANISATION-SERVICE


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: smrutisouravmoharana222@gmail.com
    password: alht xtrp wmuy ulor
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9078/realms/OriveHrm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs      

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
jwt:
  auth:
    converter:
      resource-id: orive-hrms
      principle-attribute: preferred_username